{{- if or .Values.global.podDisruptionBudget.enabled .Values.podDisruptionBudget.enabled }}
{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "testkube-worker-service.fullname" . }}
  labels:
  {{- include "testkube-worker-service.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if or .Values.podDisruptionBudget.maxUnavailable (not .Values.podDisruptionBudget.minAvailable) }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable | default 1  }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "testkube-worker-service.selectorLabels" . | nindent 6 }}
{{- end }}
