helm:
  parameters:
  - name: image.name
    value: testkubeenterprise/testkube-enterprise-ui
    forcestring: true
  - name: testkube-cloud-api.image.tag
    value: 1.10.2-rc-104dfccd
    forcestring: true
  - name: testkube-cloud-ui.image.tag
    value: 1.9.0-rc-ac0639e
    forcestring: true
