helm:
  parameters:
  - name: image.name
    value: testkubeenterprise/testkube-enterprise-ui
    forcestring: true
  - name: testkube-cloud-api.image.tag
    value: 1.9.1-rc-a3df40bd
    forcestring: true
  - name: testkube-cloud-ui.image.tag
    value: 1.8.0-rc-4ad06c7
    forcestring: true
