helm:
  parameters:
  - name: image.name
    value: testkubeenterprise/testkube-enterprise-ui
    forcestring: true
  - name: testkube-cloud-api.image.tag
    value: 1.9.3-rc-69039480
    forcestring: true
  - name: testkube-cloud-ui.image.tag
    value: 1.8.0-rc-91b720e
    forcestring: true
