helm:
  parameters:
  - name: image.name
    value: testkubeenterprise/testkube-enterprise-ui
    forcestring: true
  - name: testkube-cloud-api.image.tag
    value: 1.10.4-rc-ea41cee8
    forcestring: true
  - name: testkube-cloud-ui.image.tag
    value: 1.10.0-rc-afdaa79
    forcestring: true
