# Default values for testkube-enterprise.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # -- Run Testkube in enterprise mode (enables enterprise features)
  enterpriseMode: true
  # -- Enterprise License key
  enterpriseKey: ""
  # --
  enterpriseLicense: "LS0tLS1CRUdJTiBMSUNFTlNFIEZJTEUtLS0tLQpleUpsYm1NaU9pSnBUMGhDVW1sVVkzcDZkelUwZFVzelkzSmhha0pFTTBjclUyUjNkM0Z2TUdOcE5XZ3gKZGxncmJsZElNbTV3ZFhwTmVYUXlaV1JOU0dFMVVVbDZhVVZPWWpGT2FWbHFObUVyVTFCd1EyUmhNVEIyCmJqQklVa3R6VDFZMmIxcFdTekEwTW1oUmVYRlJTVWxsWlZVMmVrRm9LeTl3VVhkcmJtdHFObW92VWxwSgpRakJSVUVObk1XeEJNelJoWlhWNFVrRTJXWGsyVmtoUGN6a3lPRVpUTVc1Q0wzVnhTMmR0YUhSeldXZG0KVFROTFpYSlZTMHhpYTBsaldISjBRbXB5V25SR2RsVlFkM2R5UkVOWk1GTTVXVzV6Wmt4M01IUlpPRFp5ClpESldLMlZuVEZSa1MyMXVNSGRRWjJzck5ERTBjMWRwTVZSQldraEhiM2R1Vm05eFFtczBMemhxYVRjMQpXVTVHYkV0c1JVWlRhV2hyZEVObU5IaGpSV3NyYW1ScWJVZERRVEp5WmtKVGRHVlphMFF6VTNkWFFVWlkKT1RCMmNGSlBNbFJEWWxOR1VIVkdNblZ6YURkM2FtMUVOSFZTU0ROT1FYaExWVWx0UTBKQ1NVbFRlR2xTClZVeFBhSGwySzJKR1VERjNaVlJSVFhST2IzbHFSM2hvWlhSYVpUZDNjRWhpU2twak1XMVBMM3AzV0NzMwpjMjVrYXk5R1pWbFRWV2RwSzJJeE1HaHZla1JLZGtKVGVqUXhSbXN2Y1V4VlVrWkpObUZRUVZGa1ZHdEwKZVc0eGVXSlhlVzluV1ROTlptVklObEJYVVhRM1RHTkxSRGRDZVVsUVVqZFVLMDlOU1ZCb2N5OUhURzR4ClZGTnJlQzl5ZW1wWk9UbEhkMng0WlZsYUwyWjZNbmRUY1V4Uk1FMWtjMUJhVlV0ME5VTlhkMGxDYTJreQpOMUY2TURkSFUyVXZUbUYxZEhSU2EwSmxVV2hwVTJVM2J6TktkbkpIU1d0SVJYWmhZbFkwVTBobmVURlgKTm1Sd1QxVk9SMjlOZERKVFVFVnNRV3R2U1ZCTmVXUm5SM2hCVUhkMFYyTTRTbnAyZEc1MFNWVTVTMWhNClJucDVXRGwwVjFSUk56ZHRaU3RFTWxWNmFTOTRTekZXY210a2FWbDBlV1ZyWkVkaVRVRnhiWFZUVUZkNApTRmRRUlROMFJ5OVFVVVZxZFhCM1dFZGlaMlZ4VVVoNWRqUTVZMkZ3VFhSeGEyTldjVFYzZFZSb1FWbEkKTHpKTk1HSkRaV0ZCV0Vrdk9FdHRjbTFpZFZCTmFraFJVVWhEWWtneGNITmxXV3RCV25OQ2NVOUdjVmhWClVHbFRVVk56VHpSM1NUZHRlakpYUjJoT2RuZFljMWQ2ZFhKTVkzRkpUa2hvUzFscFdVdE9NVFpvYkhodApMM2xxTjFsNWJUVkpkbVpEVW5weFNIZGtkekJKZFVsRlMxTnFRa3BOYmxOR1NVbGtVVlprTjIxWVUxVmgKVWxWSFREZHhhREpMZG5ob1RqRlFZVmh6VWpoM1JsaEllRFF2Vm5VclkyaEJSSGs0Y201eE5VcEhMemRTClNUbDBVbWwyYWt4UGNIVmpVbmhzU21aTFoxVXhWMWRPTW5WRVpIZGllVk0xUVhaNWNsVlBibGhEZG10bQpORXhRTkhwNWNHTnRiMlJFVmxSeFZqUlZZVVYzY214aVdHcHBNVU5aUmpOWFYzTXJhMmRIU2pWdE5YQlgKT1ZWTFRtVkZiVTAxVTAxc1NIRlFSVUl5YUdwdmJrRjJZelpNU21ab2FVWnpWemhqVG05eFlYQk1RbFZYCmJFVk9WMGh6ZDFwSFZXZzJOMGhuVUhCdlRTOUhWVTVJTTJ4bGNGZHZWazl1Y1ZaSFFtZzNWMGt4Ym1SawpZekp4TmxkVlJETjRUbVZrWkhKRk1qRm5kblVyVmtWcFNYTlhXVmN2T1dkRE5rOUVNbFI0VVdWVk5sQlEKTWtsNlRrbEtlbkI0YjFVd1ptMUJTRFowU0VNNGJGSldiSEZMT0d4a2VuaHpZMGhYVUhONmFqTTVTV3QwCmNVaHdiMWxUVDJSVGJFUllaWGRtWml0RE5ISkNSMGRHU25sRFJHZzBOa3A2ZDBoWk5qRkVTMUl3Y0RNMQpkMWhTY3pVeWJucDNUVUp6TW5sSWFuSlRTRFZ0YkRnd1dYRTBjVXBYWVdoM05sUjRaMXBXU0VacmEwSnEKUlVkVWFWUkhiME5tYnpaYWNEUndaVXBoZVdkT1pGRlFLeTgwVERoTFJXdElWbFYyWTBOT00wMHplRTQ1ClozVjJlRFZRZFVWaWVEWlBLekZ3WVhsTE0yRkJXVms0YmxCSFkwc3dRbkZNYnpFNFZWVTJjbmQyYjIxdQpTMVZoVHpKUldsSkxaVzFtYTNoNFJWTnZkMjlRYlU5SmJ6aFZNak55TDBwT2VYTmhOMGRKY210dWEzWnYKZVRsNFJVTmthVmM1VjFGUVNHUnZWRkEyVXpCalFpOHlTRWwwYVdJeVdVVnNja2g2WjJKRGQzZGxPU3RVClVEbG5hbFU1U1RGQ1RqQkZWRWxuYzJGaGFUWlNiMHRqY1UxT1IxSjBha2hVTmt0NU5IUlBRMGRwZW10RQpSSGRxWmtvcldIQjJjalIzZEdsTWFrRjVObFpTZURWQ2FDOVpXR2RJWkU1NlJsRnBPRWd2ZDB0WVZuQTUKYm05bk0ydDRPRGxWVkVnMFUyODRUMmRhVUdGYVRHUnhlblkyVERkM2NHbGllVk00ZEdWcFRIUnpSR3cxClQwVmpkSFpaUlhKNFZ6UmpUbUpEZWxkdFRqbEpNMVZuWWtkR2REZG1lVk0zZERndlVHd3ljSGRUVERWdgpNMkl3YTFsYWJHcFpVM1p3YkdGTE5pdHpXRTVEVGtFeE5sUm1Va041UTBKblpGVkhlbVZrTm5SbGQyZEUKWWtOSFdYbFpja2R3U1ZvMlZETkVkSEpWU3pGemQxTkVSVFIwVFhabWVrbFJVREEwWWpZeWEycGtWVkJhClozVkNlbmQxYkVWbU0yd3dTV3hETm5WcWJUUTRSMXB4VFdGRFQxcDJZVVp2T1hFeFdERnlVWE5hVnpkQwpVeXRLVlZsSlJYWkdkblExTnpadU0wSXZPV1pTVkdoWU1XMXNaMFpVVmxOTVZpdHljMGsyTWpkbFZEazQKT1dOa1prOUJjSHBKYTJoMmJuTkZZV3BaYVdvNVRuVmxhMXBFVW1SUldsVnlkRGhqV21acVVscFpiV1Z0Ck5tSkpaRWt2WjB0Q1RIWm1SbFYzWTNweGJXbzNSRzFUVWtWaWJEZEJOa1Z1U1dsRk1uQjZhRFJCT0c0cgpiM1J2WVhoemVVMUxZVWRNWjBGUVVEUTRTVnBPU214VEszZHRjVmRPWlZaaFFsaG1UVVkyVDNnMGNuRk4KUkhWUWRtOVZXVE15UzJGYVlscFRVVlF2YlhkTFpXZFdZMFJCVUN0bE5uUkZhVGd3Umk5VGNreGplWGgyCk5VVkZiMUppV0doRU56WnNWbVk1WVVoVFJXdEphWGRNVUdvMFduZFplVWs1ZDBsVVVWQnhlRlkzTm1KRQpla0ZrT0hvMlVHVTJSRFZrYURkeVRUZEtSbFZEY0d4dVdrbHpiVGd5YkdFeVJrMTNNV00wY0Rsd1ZDODUKVFRSNVdEUlFkRGhRVmxaTGRYbE1abWhYUVZaM1NEZzBjWGN5Ukdoc1puaG1NVWtyVTBkd2JrNHZWMFJDCmNGVm9RazVVUVUxc1VuSkthMlZOZVVkSlMzZzFVemhYTW5wQ2JHdHFXVlJpWkc1T1VtaFhXR3RYVlVaVgpZV3BhUzBoUE15dGtRblZHTm1adVRIVmlXbm8yYm5WMFpHZFVaakEwTm05VVEyNHJSbkpIWkdwcWJrWjYKZFRaTVdHcG1Ta0ZuWldaTWJXZGpXVm8zY0d0UGMxQnZSVE5LU0hWbVdIaGxSVkJ3WWpGVE4xbDJXRFJ0ClpGbERiR3B0U2twUVoydFBNbk5QZW13MGNURXlXVVk0TTBsU1ZXRTJOazA1TnpkUFdtcGFRV1ZpTW1obgpRMWhxVVdSc1pWVlBiSFJuVkN0MFNIQjVjazVXWTJvclYxaEdVV015VlhoU1dESlVXRFZhV1dKS2FuZzIKUm5wSFluZFhSMWh2U2tKeWJFODFablYzTDFSaVVFMTZaV3REYTJOcVVGZHBhelp0WXpsRVkwSllZbE0yCmVFRlZUMHhzZUdrMFV6TnVOR2hsZDFWc1QyUnlTWGN5TVM4dlRtRnNLMGx6UVRndlVXVnRSakJvVUdVNAplWFZ6YVRVcmVFZFJiV3RGWldKTFQxYzRVVXRQZWt4bFZWY3pWWEZUVEUxMk1rVnNaazh6Y1VFNGMwbFEKWmpjdldTOHliVXBYU0hkak9UQkZPRlJZU1ZOeVdIUTVlbU16YWpKYVR6QTFhVFFyYWpWM2J6QjRNbGxUCk4zTkZRbEpUVVN0UmR5OW5WSHBYTDIxNVZuWkhRVnBsZUdaeksxQmhVWEpsZUd4TU0zTjRhMEZpZFhacgpTeXR6YTJ3dmJHVlhNbGRoY0U0MFZtMTBTQzlhVG5oV1dtZzJUblJKUlZGUFMwSldTR1J2WjNVNWMwWkIKWjFKMFpraFZiR2MzVG1KTVFXNUJXRFJXVlM4Mk5HTnlTV1V6YjJ4eFNHSkJWMDlUWmtkUVN6Qk1ZbmR4CmRFUmpkbU5hVFhVeVNEaFBhMHR0TlhkUmNEWlpSM2xyTkc1SlJrTTBOazl4WkhjNVNWTXhZbXByTVhSUwpUMWhpZEdGVmFWSXpkV1ZMY0ZaUmMwZFFSRWQwTW5OcGJHTk1PVWQwVjB0M2ExVkJRbWxMUjBzNUsyUnMKU2s4NE9IZFFibkJaVlhZMFpuWnVaSGhUUmxKRmNsWnNaRFZDU3pkbGVEbHpSVlJRTkhoMGIwdDNVRmx4CmFGbFBUMU5LUVRWMlRIQkhZV3hwUmpaNlNtWlJMM28wTldWelUwdGtZa3RvUTJwSmFESTNLMkZ2UVVSdwpORzVDVDA5MFpHMVZlbUpVZWxKc1pFNDRZMWRMWlc0MmFXeFhVbGhQU0RoVk1YUXdVa1JtUkd4NlVsSkUKU1RNelRrMUhjelZWWVhRNGFrMHdha05VVGpSb2VuZExZVUpaVjNsWldISmxRVlEyY1U5dEswRmhSV2Q0Ck5FUnlLMjFwYVdOWFoyNXdWSGw2Y1hwYU1VTkNObEZGWVVObVNsTnBTVnAxUkV0V1pHTk5WRUY1YzNRdwpZVWRXVG5GcU0xQnpia3BYUm1SdFUxYzRObG94UVRGd1N6aHhlRFJKTkN0NFR6RkdlSHBzTlZaVFluUnUKYUdNMlpYbHlablVyUmsxNE1WRndUVkE1U0c1TloxTkRkaTlPU0ROdVNteHNjbEJsWVVwNmNHdGFhVXhZCmRDdGlialpIV0RSd1NVSmhOVWxvZW5kdE9GUnFkWFJyYzFoV04yRk9WazE2TURGUE4zaFBVa1kxZG1OUQpkVVZCYW5ZNVZUVmFSVnBaYkZSTWVUTkpNM1Y0V0V4dVVubE5WV3BJWlVjeVlTdDFkVm93WmpoYVFtRnEKZWxoRWVWaHBlV1pGSzNwbVUySkhNREprV1M5YVRtZHlUWEl2V1RKRFRGRXdVV1pyVWxwRFFqRXlWVlV4CmRpOHdhV05uYkVST1FUTkJUREphWVhsQ1VsRXdaMUUzVDAxR1RESkxZMFoxTVdGMU1qVXhjR3N3VDNWagpWMGRpUzJGMVEwb3dTbkpzUW5SbVNtUjNSRTQyUVRCM1JFdGtSREpTTW1SRWNsSm9kVkJUV21SRlMwUlQKWkhsNlVGTklaQ3RaYUVOMEswOVBWbVZVVlRoWmFrMWxUakJqYzJGeGIwZFdUMUJDZWpWelJYVlpUVXhSClVrMXZUVE5LYkVSRlIyOVpSRVpDWW14VU0zaFVXalZ5WjJsTmVUUTJkRFEyYkUxNmFXZzFTR05CUTNORApVa2xpVmpkaFpVZzVhVWMzTjJaVVUwaElRbk5xVWpKaFNrcHRPVE5EZVZJeFYzZGhLMjFvTmk4d01sWlUKY2s5NVJtcHhSRzlWUWpBclUzUjZZbFEyY2pKaWRreEtRMWRCT0VOM1JIcEZiamRUYzBGdGFEZEtkRzlRCmMxUk1OVGx2UTFndlFtZGxWRFpwWVc1ek1GVlhWVUZXY0RSNWVHeHVkelJMVDBOVWJYWjZWRWdyUkdwegpSa2t2VURkNGEydDFOSFZNZURkT016UlJjR2hCUWtreGRGUjFZVk5CTkc1dk1FZEhZek15UlU5NFRtVjEKUWxoTk1UbDBVMUpxV0RJeVNVTjJPRUpCZUVONGEyb3lVVk5HY1hCR2IwVnlaVGxGWWxOSlFVVXhiMUZMClVXTk5hbGx0V0VscmRrY3dSSGRFUVVka1RpOWhURzR4ZW14TFpWTmhSemRwTTNacmQxbFZaak5WZGxScQpaRkJCSzFaT1VFczNTbEV6YW1ZeVlXWk9LMjlRY1Vwd05rWkZMMnN6V21STFFtcDBlWE5QTDFKMVVEZGwKVUZSdmFqSnljM1ZEWkhCMmJqUnVjblpFU1U1SWJWQkpjRWg1UzFaeFVVcFJLMnhJWkdrM05IVndVVGd3CmFIaDZUVkZCUzFaSWFYTllZakJ1V2xSUEszVnljV2t2ZWpKdWFUaFBibVpPTTFVeVltdFpSSFpMUTJVMgpWbWRpTDJKd1lYZDNSRXRXU0djeU5teHZaRzFVSzNrdldISnZSVXhZY2t3eGQwNDBkV2M5UFM1Q1RuUTQKZFVGVFJFaHhiblJNTm5WWkxtTjVhRmN3Y1dRdlUwZHVWakIwTmxCcldpOU9SV2M5UFNJc0luTnBaeUk2CklqRlJabGg0Tnk5elpqWkhhbGhzVkdSbVNFaFVNMDFEZEZNeVYyWnBZMFJuTm5sWVZEazFVME12YzJ4TwphVVJ6U1RBeFZqWXdPSGxGTUhadU9YWnVlRGhNU210bFdGSm1jSFE1Wlc5UFoyaENhRzgwYjBGblBUMGkKTENKaGJHY2lPaUpoWlhNdE1qVTJMV2RqYlN0bFpESTFOVEU1SW4wPQotLS0tLUVORCBMSUNFTlNFIEZJTEUtLS0tLQo="
  # -- Toggle whether to enable offline license activation in Enterprise mode
  enterpriseOfflineAccess: false
  # -- Domain under which to create Ingress rules
  domain: ""
  # -- UI subdomain which get prepended to the domain
  uiSubdomain: "dashboard"
  # -- REST API subdomain which get prepended to the domain
  restApiSubdomain: "api"
  # -- gRPC API subdomain which get prepended to the domain
  grpcApiSubdomain: "agent"
  # -- Websocket API subdomain which get prepended to the domain
  websocketApiSubdomain: "websockets"
  # -- TLS provider (possible values: "", "cert-manager")
  certificateProvider: "cert-manager"
  certManager:
    # -- Certificate Issuer ref (only used if `provider` is set to `cert-manager`)
    issuerRef: ""
  # -- Image pull secrets to use for testkube-cloud-api and testkube-cloud-ui
  imagePullSecrets: []
## Testkube Cloud API chart parameters
testkube-cloud-api:
  fullnameOverride: testkube-enterprise-api
  image:
    repository: kubeshop/testkube-enterprise-api
    tag: 1.2.0-dev-ba71c83
  api:
    tls:
      tlsSecret: testkube-enterprise-api-tls
    migrations:
      # -- Toggle whether to run database migrations
      enabled: true
      # -- Toggle whether to enable pre-install & pre-upgrade hooks (should be disabled if mongo is installed using this chart)
      useHelmHooks: false
    mongo:
      # -- Mongo DSN connection string
      dsn: "mongodb://testkube-enterprise-mongodb:27017"
      # -- Mongo database name
      database: "testkubeEnterpriseDB"
    nats:
      # -- NATS URI
      uri: "nats://testkube-enterprise-nats:4222"
    minio:
      # -- MinIO endpoint
      endpoint: "testkube-enterprise-minio:9000"
      # -- S3 region
      region: ""
      # -- MinIO access key id
      accessKeyId: "testkube-enterprise"
      # -- MinIO secret access key
      secretAccessKey: "t3stkub3-3nt3rpr1s3"
      # -- MinIO token
      token: ""
      # -- Credentials secret ref (secret should contain keys: MINIO_ACCESS_KEY_ID, MINIO_SECRET_ACCESS_KEY, MINIO_TOKEN) (default is `testkube-cloud-minio-secret`)
      credsSecretRef: ""
      # -- Expiration period in days
      expirationPeriod: 0
      # -- Should be set to `true` if MinIO is exposed through HTTPS
      secure: false
    sendgrid:
      # -- Sendgrid API key
      apiKey: ""
      # -- Secret API key secret ref (secret must contain key SENDGRID_API_KEY) (default is `sendgrid-api-key`)
      secretRef: ""
    agent:
      hide: false
      # -- Agent host (without protocol) is used for building agent install commands (if blank, api will autogenerate it based on the value of `global.domain`)
      host: ""
      # -- Agent port - used for building agent install commands
      port: 443
    oauth:
      # -- OAuth secret ref for OAuth configuration (secret must contain keys: OAUTH_CLIENT_ID, OAUTH_CLIENT_SECRET, OAUTH_ISSUER_URL, OAUTH_REDIRECT_URI) (default is `testkube-cloud-oauth-secret`)
      secretRef: ""
      # -- OAuth Client ID for the configured static client in Dex
      clientId: "testkube-enterprise"
      # -- OAuth Client ID for the configured static client in Dex
      clientSecret: "QWkVzs3nct6HZM5hxsPzwaZtq"
      # -- If oauth.secretRef is empty (""), then oauth.redirectUri field will be used for the OAuth redirect URI
      redirectUri: ""
    # -- S3 bucket in which to store logs & artifacts
    outputsBucket: testkube-cloud-outputs
  minio:
    fullnameOverride: testkube-enterprise-minio
    # -- Toggle whether to install MinIO
    enabled: true
    # -- Minio extra vars
    extraEnvVars: {}
    # - name: FOO
    #   value: BAR

    # Read more about access modes here: http://kubernetes.io/docs/user-guide/persistent-volumes/#access-modes
    # -- PVC Access Modes for Minio. The volume is mounted as read-write by a single node.
    accessModes:
      - ReadWriteOnce
    # -- Node labels for pod assignment.
    nodeSelector: {}
    # ref: https://cloud.google.com/kubernetes-engine/docs/how-to/prepare-arm-workloads-for-deployment#node-affinity-multi-arch-arm
    # -- Tolerations to schedule a workload to nodes with any architecture type. Required for deployment to GKE cluster.
    tolerations: []
    # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
    # Note: podAffinityPreset, podAntiAffinityPreset, and nodeAffinityPreset will be ignored when it's set
    # -- Affinity for pod assignment.
    affinity: {}
    # -- Custom service account for MinIO Deployment resource (overrides service account creation)
    customServiceAccountName: ""
    serviceAccount:
      # -- Specifies whether a service account should be created
      create: false
      # -- Additional annotations to add to the ServiceAccount resource
      annotations: {}
      # -- Additional labels to add to the ServiceAccount resource
      labels: {}
      # -- The name of the service account to use.
      name: ""
    credentials:
      # -- Root username
      accessKeyId: "testkube-enterprise"
      # -- Root password
      secretAccessKey: "t3stkub3-3nt3rpr1s3"
    persistence:
      # -- PVC Storage Request for MinIO. Should be available in the cluster.
      storage: 10Gi
    # -- MinIO Resources settings
    resources: {}
    # ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
    # -- MinIO Pod Security Context
    podSecurityContext: {}
    # ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
    # -- Security Context for MinIO container
    securityContext: {}
  prometheus:
    enabled: true
testkube-cloud-ui:
  fullnameOverride: testkube-enterprise-ui
  image:
    repository: kubeshop/testkube-enterprise-ui
    tag: 1.0.2
  ingress:
    # -- Name of the TLS secret which contains the certificate files
    tlsSecretName: testkube-enterprise-ui-tls
## NATS chart parameter
## For more configuration parameters of NATS chart please look here: https://docs.nats.io/running-a-nats-service/nats-kubernetes/helm-charts
nats:
  fullnameOverride: testkube-enterprise-nats
  tolerations: []
  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  # -- NATS Pod Security Context
  securityContext: {}
  cluster:
    # -- Enable cluster mode (HA)
    enabled: true
    # -- NATS cluster replicas
    replicas: 3
  # NATS container settings
  nats:
    enabled: true
    # ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
    # -- Security Context for NATS container
    securityContext: {}
    # -- NATS resource settings
    resources: {}
    limits:
      # -- Max payload
      maxPayload: 8MB
  # Reloader container settings
  reloader:
    # ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
    # -- Security Context for Reloader container
    securityContext: {}
  # NATS Box container settings
  natsbox:
    # ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
    # -- Security Context for NATS Box container
    securityContext: {}
    # -- NATS Box tolerations settings
    tolerations: []
  # Exporter container settings
  exporter:
    # ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
    # -- Security Context for Exporter container
    securityContext: {}
    # -- Exporter resources settings
    resources: {}
## MongoDB chart parameters
## For more configuration parameters of MongoDB chart please look here: https://github.com/bitnami/charts/tree/master/bitnami/mongodb#parameters
mongodb:
  # -- Toggle whether to install MongoDB
  enabled: true
  # -- MongoDB fullname override
  fullnameOverride: "testkube-enterprise-mongodb"
  # MongoDB Auth settings
  auth:
    # -- Toggle whether to enable MongoDB authentication
    enabled: false
    # rootPassword: "123DefaultOne321"
  # -- MongoDB resource settings
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
  tolerations: []
  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  # -- MongoDB Pod Security Context
  podSecurityContext: {}
  # For OpenShift clusters use the following settings:
  #  fsGroup: 1000670000

  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  # -- Security Context for MongoDB container
  containerSecurityContext: {}
  # For OpenShift clusters use the following settings:
  #  runAsGroup: 1000670000
## Dex chart parameters
## For more configuration parameters of NATS chart please look here: https://github.com/dexidp/helm-charts
dex:
  # -- Toggle whether to install Dex
  enabled: true
  # -- Override default issuer config which is constructed from global.domain
  issuer: ""
  fullnameOverride: testkube-enterprise-dex
  image:
    # -- Dex image tag (https://ghcr.io/dexidp/dex)
    tag: v2.36.0-alpine
  configSecret:
    # -- This should be set to `false` so Dex does not create the config secret. Refer to the `createCustom` field for more info on creating config secret.
    create: false
    # -- Toggle whether to create a custom config secret for Dex (templates/dex-config-secret.yaml). If set to `true`, the `configTemplate` field will be used to generate the config secret.
    createCustom: true
    # -- The name of the secret to mount as configuration in the pod. Set `createCustom: false` and edit the secret manually to use a custom config secret.
    name: "testkube-enterprise-dex-config"
  # -- Inline Dex configuration which will be used to generate the config secret.
  configTemplate:
    # -- If provided, it will completely override the default config (`base` and `additionalConfig`). This is useful if you want to use a custom config file.
    customConfig: ""
    base: |
      logger:
        level: debug
        format: json
      storage:
        type: kubernetes
        config:
          inCluster: true
    # -- Additional config which will be appended to the config like `staticClients`, `staticPasswords ,`connectors`...
    additionalConfig: ""
  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  # -- Security Context for MongoDB container
  securityContext: {}
  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  # -- MongoDB Pod Security Context
  podSecurityContext:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits: {}
  ingress:
    # -- Toggle whether to enable ingress for Dex
    enabled: true
    # -- Testkube Enterprise supports only NGINX Controller currently
    className: nginx
    hosts:
      - host: 'api.{{ .Values.global.domain }}'
        paths:
          - path: /idp
            pathType: Prefix
    tls:
      - secretName: testkube-enterprise-api-tls
        hosts:
          - 'api.{{ .Values.global.domain }}'
