{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ui-external-secrets
spec:
  data:
{{- range $key, $value := .Values.externalSecrets.keys }}
  - remoteRef:
      key: {{ $value }}
    secretKey: {{ $key }}
{{ end }}
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.clusterSecretStoreName }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: ui-external-secrets
{{- end }}
