{{- if and (hasKey .Values "apiSecrets") (not (empty .Values.apiSecrets)) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-external-secrets
spec:
  data:
{{- range $key, $value := .Values.apiSecrets }}
  - remoteRef:
      key: {{ $value }}
    secretKey: {{ $key }}
{{ end }}
  refreshInterval: 60s
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: api-external-secrets
{{- end }}
---
{{- if and (hasKey .Values "uiSecrets") (not (empty .Values.uiSecrets)) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ui-external-secrets
spec:
  data:
{{- range $key, $value := .Values.uiSecrets }}
  - remoteRef:
      key: {{ $value }}
    secretKey: {{ $key }}
{{ end }}
  refreshInterval: 60s
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: ui-external-secrets
{{- end }} 
