{{- range $key, $value := .Values.apiSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $value | lower | replace "_" "-" }}
spec:
  data:
  - remoteRef:
      key: {{ $value }}
    secretKey: {{ $key }}
  refreshInterval: 60s
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ $value | lower | replace "_" "-" }}
---
{{ end }}
