{{- if and .Values.api.tls.serveHTTPS (eq .Values.global.certificateProvider "cert-manager") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "testkube-cloud-api.fullname" . }}
  labels:
    {{- include "testkube-cloud-api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  secretName: {{ .Values.api.tls.tlsSecret }}
  dnsNames:
    {{- if .Values.restIngress.enabled }}
    - {{ include "testkube-cloud-api.ingress.restHost" . | quote }}
    {{- end }}
    {{- if .Values.grpcIngress.enabled }}
    - {{ include "testkube-cloud-api.ingress.grpcHost" . | quote }}
    {{- end }}
    {{- if .Values.websocketsIngress.enabled }}
    - {{ include "testkube-cloud-api.ingress.websocketsHost" . | quote }}
    {{- end }}
  {{- with .Values.api.tls.certManager.duration }}
  duration: {{ . | quote }}
  {{- end }}
  issuerRef:
    name: {{ required ".Values.global.certManager.issuerRef must be set when provider is cert-manager" .Values.global.certManager.issuerRef }}
    kind: {{ .Values.api.tls.certManager.issuerKind }}
    group: {{ .Values.api.tls.certManager.issuerGroup }}
{{- end }}
