apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "testkube-cloud-api.fullname" . }}
  labels:
    {{- include "testkube-cloud-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "testkube-cloud-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "testkube-cloud-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "testkube-cloud-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.api.mongoDsnSecretRef }}
            - name: API_MONGO_DSN
              valueFrom:
                secretKeyRef:
                  key: MONGO_DSN
                  name: {{ .Values.api.mongoDsnSecretRef }}
            {{- else }}
            - name: API_MONGO_DSN
              value: {{ .Values.api.mongoDsn }}
            {{- end }}
            - name: API_MONGO_DB
              value: {{ .Values.api.mongoDb }}
            {{- if .Values.api.oauth.secretRef }}
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: OAUTH_CLIENT_ID
                  name: {{ .Values.api.oauth.secretRef }}
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: OAUTH_CLIENT_SECRET
                  name: {{ .Values.api.oauth.secretRef }}
            - name: OAUTH_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  key: OAUTH_ISSUER_URL
                  name: {{ .Values.api.oauth.secretRef }}
            - name: OAUTH_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  key: OAUTH_REDIRECT_URI
                  name: {{ .Values.api.oauth.secretRef }}
            {{- end }}
            {{- if .Values.api.oauth.clientId }}
            - name: OAUTH_CLIENT_ID
              value: {{ .Values.api.oauth.clientId }}
            {{- end }}
            {{- if .Values.api.oauth.clientSecret }}
            - name: OAUTH_CLIENT_SECRET
              value: {{ .Values.api.oauth.clientSecret }}
            {{- end }}
            {{- if .Values.api.oauth.issuerUrl }}
            - name: OAUTH_ISSUER_URL
              value: {{ .Values.api.oauth.issuerUrl }}
            {{- end }}
            {{- if .Values.api.oauth.redirectUri }}
            - name: OAUTH_REDIRECT_URI
              value: {{ .Values.api.oauth.redirectUri }}
            {{- end }}
            - name: OAUTH_MASTER_REDIRECT_URI
              value: {{ .Values.api.oauth.masterRedirectUri }}
            - name: NATS_URI
              value: {{ .Values.api.natsUri }}
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
            {{- if .Values.prometheus.enabled }}
            - name: metrics
              containerPort: 9000
              protocol: TCP
            {{- end }}
            - name: grpc
              containerPort: 8089
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
