apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "testkube-cloud-api.fullname" . }}
  labels:
    {{- include "testkube-cloud-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "testkube-cloud-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "testkube-cloud-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "testkube-cloud-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ENTERPRISE_MODE
              value: "{{ .Values.global.enterpriseMode }}"
            - name: METRICS_LISTEN_ADDR
              value: "0.0.0.0:9100"
            {{- if .Values.payments.enabled }}
            - name: PAYMENTS_PORTAL_CONFIGURATION_ID
              {{- if .Values.payments.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: PAYMENTS_PORTAL_CONFIGURATION_ID
                  name: {{ .Values.payments.secretRef }}
              {{- else }}
              value: {{ .Values.payments.portalConfigurationId }}
              {{- end }}
            - name: PAYMENTS_ENDPOINT_SECRET
              {{- if .Values.payments.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: PAYMENTS_ENDPOINT_SECRET
                  name: {{ .Values.payments.secretRef }}
              {{- else }}
              value: {{ .Values.payments.endpointSecret }}
              {{- end }}
            - name: PAYMENTS_API_KEY
              {{- if .Values.payments.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: PAYMENTS_API_KEY
                  name: {{ .Values.payments.secretRef }}
              {{- else }}
              value: {{ .Values.payments.apiKey }}
              {{- end }}
            {{- end }}
            {{- if .Values.analytics.segmentio.enabled }}
            - name: SEGMENTIO_WRITE_KEY
              {{- if .Values.analytics.segmentio.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: SEGMENTIO_WRITE_KEY
                  name: {{ .Values.analytics.segmentio.secretRef }}
              {{- else }}
              value: {{ .Values.analytics.segmentio.writeKey }}
              {{- end }}
            {{- end }}
            - name: SENDGRID_API_KEY
              {{- if .Values.api.sendgrid.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: SENDGRID_API_KEY
                  name: {{ .Values.api.sendgrid.secretRef }}
              {{- else }}
              value: "{{ .Values.api.sendgrid.apiKey }}"
              {{- end }}
            - name: API_MONGO_DSN
              {{- if .Values.api.mongo.dsnSecretRef }}
              valueFrom:
                secretKeyRef:
                  key: MONGO_DSN
                  name: {{ .Values.api.mongo.dsnSecretRef }}
              {{- else }}
              value: {{ .Values.api.mongo.dsn }}
              {{- end }}
            - name: API_MONGO_DB
              value: {{ .Values.api.mongo.database }}
            - name: OAUTH_CLIENT_ID
              {{- if .Values.api.oauth.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: OAUTH_CLIENT_ID
                  name: {{ .Values.api.oauth.secretRef }}
              {{- else }}
              value: "{{ .Values.api.oauth.clientId }}"
              {{- end }}
            - name: OAUTH_CLIENT_SECRET
              {{- if .Values.api.oauth.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: OAUTH_CLIENT_SECRET
                  name: {{ .Values.api.oauth.secretRef }}
              {{- else }}
              value: "{{ .Values.api.oauth.clientSecret }}"
              {{- end }}
            - name: OAUTH_ISSUER_URL
              {{- if .Values.api.oauth.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: OAUTH_ISSUER_URL
                  name: {{ .Values.api.oauth.secretRef }}
              {{- else }}
              value: {{ if .Values.api.oauth.issuerUrl }}{{ .Values.api.oauth.issuerUrl }}{{ else }}https://{{ .Values.global.restApiSubdomain }}.{{ .Values.global.domain }}/idp{{ end }}
              {{- end }}
            - name: OAUTH_REDIRECT_URI
              {{- if .Values.api.oauth.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: OAUTH_REDIRECT_URI
                  name: {{ .Values.api.oauth.secretRef }}
              {{- else }}
              value: "{{ if .Values.api.oauth.redirectUri }}{{ .Values.api.oauth.redirectUri }}{{ else }}https://{{ .Values.global.restApiSubdomain }}.{{ .Values.global.domain }}/auth/callback{{ end }}"
              {{- end }}
            - name: NATS_URI
              value: {{ .Values.api.nats.uri }}
            {{- $dashboardAddress := "" }}
            {{- if .Values.api.dashboardAddress }}
            {{- $dashboardAddress = .Values.api.dashboardAddress }}
            {{- else }}
            {{- $dashboardAddress = printf "https://%s.%s" .Values.global.uiSubdomain .Values.global.domain }}
            {{- end }}
            - name: ALLOWED_EXTERNAL_REDIRECT_URIS
              value: {{ if .Values.api.oauth.allowedExternalRedirectURIs }}{{ .Values.api.oauth.allowedExternalRedirectURIs }}{{ else }}{{ $dashboardAddress }}{{ end }}
            {{- if .Values.api.agent.hide }}
            - name: HIDE_AGENT_HOST
              value: "{{ .Values.api.agent.hide }}"
            {{- end }}
            - name: AGENT_HOST
              value: {{ if .Values.api.agent.host }}{{ .Values.api.agent.host }}{{ else }}{{ .Values.global.grpcApiSubdomain }}.{{ .Values.global.domain }}{{ end }}
            - name: AGENT_PORT
              value: "{{ if .Values.api.tls.serveHTTPS }}443{{ else }}{{ .Values.service.grpcPort }}{{ end }}"
            - name: API_ADDRESS
              value: {{ if .Values.api.apiAddress }}{{ .Values.api.apiAddress }}{{ else }}https://{{ .Values.global.restApiSubdomain }}.{{ .Values.global.domain }}{{ end }}
            - name: DASHBOARD_ADDRESS
              value: {{ $dashboardAddress }}
            - name: USE_TLS
              value: "{{ .Values.api.tls.serveHTTPS }}"
            - name: TLS_CERT
              value: "{{ .Values.api.tls.certPath }}"
            - name: TLS_KEY
              value: "{{ .Values.api.tls.keyPath }}"
            - name: OUTPUTS_BUCKET
              value: "{{ .Values.api.outputsBucket }}"
            {{- if .Values.minio.enabled }}
            - name: MINIO_ENDPOINT
              value: "{{ .Values.api.minio.endpoint }}"
            - name: MINIO_REGION
              value: "{{ .Values.api.minio.region }}"
            - name: MINIO_SSL
              value: "{{ .Values.api.minio.secure }}"
            - name: MINIO_EXPIRATION
              value: "{{ .Values.api.minio.expirationPeriod }}"
            - name: MINIO_ACCESS_KEY_ID
              {{- if .Values.api.minio.credsSecretRef }}
              valueFrom:
                secretKeyRef:
                  key: MINIO_ACCESS_KEY_ID
                  name: {{ .Values.api.minio.credsSecretRef }}
              {{- else }}
              value: "{{ .Values.api.minio.accessKeyId }}"
              {{- end }}
            - name: MINIO_SECRET_ACCESS_KEY
              {{- if .Values.api.minio.credsSecretRef }}
              valueFrom:
                secretKeyRef:
                  key: MINIO_SECRET_ACCESS_KEY
                  name: {{ .Values.api.minio.credsSecretRef }}
              {{- else }}
              value: "{{ .Values.api.minio.secretAccessKey }}"
              {{- end }}
            - name: MINIO_TOKEN
              {{- if .Values.api.minio.credsSecretRef }}
              valueFrom:
                secretKeyRef:
                  key: MINIO_TOKEN
                  name: {{ .Values.api.minio.credsSecretRef }}
              {{- else }}
              value: "{{ .Values.api.minio.token }}"
              {{- end }}
            {{- end }}
            {{- range $k, $v := .Values.additionalEnv }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end}}
          ports:
            - name: {{ if .Values.api.tls.serveHTTPS }}https{{ else }}http{{ end }}
              containerPort: {{ if .Values.api.tls.serveHTTPS }}{{ .Values.api.tls.apiPort }}{{ else }}8090{{ end }}
              protocol: TCP
            - name: {{ if .Values.api.tls.serveHTTPS }}grpcs{{ else }}grpcs{{ end }}
              containerPort: {{ if .Values.api.tls.serveHTTPS }}{{ .Values.api.tls.agentPort }}{{ else }}8089{{ end }}
              protocol: TCP
            {{- if .Values.prometheus.enabled }}
            - name: metrics
              containerPort: 9100
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              scheme: {{ if .Values.api.tls.serveHTTPS }}HTTPS{{ else }}HTTP{{ end }}
              port: {{ if .Values.api.tls.serveHTTPS }}https{{ else }}http{{ end }}
          readinessProbe:
            httpGet:
              path: /health
              scheme: {{ if .Values.api.tls.serveHTTPS }}HTTPS{{ else }}HTTP{{ end }}
              port: {{ if .Values.api.tls.serveHTTPS }}https{{ else }}http{{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.api.tls.serveHTTPS }}
          volumeMounts:
            - mountPath: /tmp/serving-cert/crt.pem
              readOnly: true
              name: serving-cert
              subPath: tls.crt
            - mountPath: /tmp/serving-cert/key.pem
              readOnly: true
              name: serving-cert
              subPath: tls.key
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.api.tls.serveHTTPS }}
      volumes:
        - name: serving-cert
          secret:
            secretName: {{ .Values.api.tls.tlsSecret }}
      {{- end }}