apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "testkube-cloud-api.fullname" . }}
  labels:
    {{- include "testkube-cloud-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "testkube-cloud-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "testkube-cloud-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- else if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "testkube-cloud-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DEMO_ORGANIZATION_ID
              value: "{{ .Values.demoOrganizationId }}"
            - name: ENTERPRISE_MODE
              value: "{{ .Values.global.enterpriseMode }}"
            {{- if .Values.global.enterpriseMode }}
            - name: ENTERPRISE_OFFLINE_ACTIVATION
              value: "{{ .Values.global.enterpriseOfflineAccess }}"
            {{- end }}
            {{- if .Values.global.enterpriseMode }}
            - name: ENTERPRISE_LICENSE_KEY
              {{- if .Values.global.enterpriseLicenseSecretRef }}
              valueFrom:
                secretKeyRef:
                  key: LICENSE_KEY
                  name: {{ .Values.global.enterpriseLicenseSecretRef }}
              {{- else }}
              value: "{{ .Values.global.enterpriseLicenseKey }}"
              {{- end }}
            {{- end }}
            {{- if .Values.global.enterpriseLicenseFile }}
            - name: ENTERPRISE_LICENSE_FILE
              value: "{{ .Values.global.enterpriseLicenseFile }}"
            {{- end }}
            {{- if .Values.api.debug.enableHttp2Logs }}
            - name: GODEBUG
              value: http2debug=2
            {{- end }}
            {{- if .Values.api.debug.enableGrpcServerLogs }}
            - name: ENABLE_GRPC_VERBOSE_LOGGING
              value: "true"
            {{- end }}
            {{- if .Values.api.agent.keepAlive }}
            - name: ENABLE_GRPC_KEEP_ALIVE
              value: "true"
            {{- end }}
            {{- if .Values.ai.secretRef }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.ai.secretKey }}
                  name: {{ .Values.ai.secretRef }}
            {{- else if .Values.ai.apiKey }}
            - name: OPENAI_API_KEY
              value: "{{ .Values.ai.apiKey }}"
            {{- end }}
            - name: HEALTHCHECK_DISTRIBUTED_LOCK
              value: "{{ .Values.api.agent.healthcheck.lock }}"
            - name: INVITE_MODE
              value: "{{ .Values.api.inviteMode }}"
            {{- if eq .Values.api.inviteMode "email" }}
            - name: SMTP_HOST
              value: "{{ .Values.api.smtp.host }}"
            - name: SMTP_PORT
              value: "{{ .Values.api.smtp.port }}"
            - name: SMTP_USER
              value: "{{ .Values.api.smtp.username }}"
            - name: SMTP_PASS
              {{- if .Values.api.smtp.passwordSecretRef }}
              valueFrom:
                secretKeyRef:
                  key: SMTP_PASS
                  name: {{ .Values.api.smtp.passwordSecretRef }}
              {{- else }}
              value: "{{ .Values.api.smtp.password }}"
              {{- end }}
            {{- end }}
            - name: FROM_EMAIL
              value: "{{ .Values.api.email.fromEmail }}"
            - name: FROM_NAME
              value: "{{ .Values.api.email.fromName }}"
            - name: ROOT_DOMAIN
              value: "{{ .Values.global.domain }}"
            - name: METRICS_LISTEN_ADDR
              value: "0.0.0.0:9100"
            {{- if .Values.payments.enabled }}
            - name: PAYMENTS_PORTAL_CONFIGURATION_ID
              {{- if .Values.payments.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: PAYMENTS_PORTAL_CONFIGURATION_ID
                  name: {{ .Values.payments.secretRef }}
              {{- else }}
              value: {{ .Values.payments.portalConfigurationId }}
              {{- end }}
            - name: PAYMENTS_ENDPOINT_SECRET
              {{- if .Values.payments.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: PAYMENTS_ENDPOINT_SECRET
                  name: {{ .Values.payments.secretRef }}
              {{- else }}
              value: {{ .Values.payments.endpointSecret }}
              {{- end }}
            - name: PAYMENTS_API_KEY
              {{- if .Values.payments.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: PAYMENTS_API_KEY
                  name: {{ .Values.payments.secretRef }}
              {{- else }}
              value: {{ .Values.payments.apiKey }}
              {{- end }}
            {{- end }}
            {{- if .Values.analytics.segmentio.enabled }}
            - name: SEGMENTIO_WRITE_KEY
              {{- if .Values.analytics.segmentio.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: SEGMENTIO_WRITE_KEY
                  name: {{ .Values.analytics.segmentio.secretRef }}
              {{- else }}
              value: {{ .Values.analytics.segmentio.writeKey }}
              {{- end }}
            {{- end }}
            {{- if .Values.analytics.hubspot.enabled }}
            - name: HUBSPOT_API_KEY
              {{- if .Values.analytics.hubspot.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: HUBSPOT_API_KEY
                  name: {{ .Values.analytics.hubspot.secretRef }}
              {{- else }}
              value: {{ .Values.analytics.hubspot.apiKey }}
              {{- end }}
            {{- end }}
              {{- if .Values.api.sendgrid.secretRef }}
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  key: SENDGRID_API_KEY
                  name: {{ .Values.api.sendgrid.secretRef }}
              {{- else if .Values.api.sendgrid.apiKey }}
            - name: SENDGRID_API_KEY
              value: "{{ .Values.api.sendgrid.apiKey }}"
              {{- end }}
              {{- if .Values.api.mongo.dsnSecretRef }}
            - name: API_MONGO_DSN
              valueFrom:
                secretKeyRef:
                  key: MONGO_DSN
                  name: {{ .Values.api.mongo.dsnSecretRef }}
              {{- else if .Values.api.mongo.dsn }}
            - name: API_MONGO_DSN
              value: {{ .Values.api.mongo.dsn }}
              {{- end }}
            - name: API_MONGO_DB
              value: {{ .Values.api.mongo.database }}
              {{- if .Values.api.oauth.secretRef }}
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: OAUTH_CLIENT_ID
                  name: {{ .Values.api.oauth.secretRef }}
              {{- else if .Values.api.oauth.clientId }}
            - name: OAUTH_CLIENT_ID
              value: "{{ .Values.api.oauth.clientId }}"
              {{- end }}
              {{- if .Values.api.oauth.secretRef }}
            - name: OAUTH_CLI_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: OAUTH_CLI_CLIENT_ID
                  name: {{ .Values.api.oauth.secretRef }}
              {{- else if .Values.api.oauth.cliClientId }}
            - name: OAUTH_CLI_CLIENT_ID
              value: "{{ .Values.api.oauth.cliClientId }}"
              {{- end }}
              {{- if .Values.api.oauth.secretRef }}
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: OAUTH_CLIENT_SECRET
                  name: {{ .Values.api.oauth.secretRef }}
              {{- else if .Values.api.oauth.clientSecret }}
            - name: OAUTH_CLIENT_SECRET
              value: "{{ .Values.api.oauth.clientSecret }}"
              {{- end }}
              {{- if .Values.api.oauth.secretRef }}
            - name: OAUTH_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  key: OAUTH_ISSUER_URL
                  name: {{ .Values.api.oauth.secretRef }}
              {{- else }}
            - name: OAUTH_ISSUER_URL
              value: {{ if .Values.global.dex.issuer}}{{ .Values.global.dex.issuer }}{{ else if .Values.api.oauth.issuerUrl }}{{ .Values.api.oauth.issuerUrl }}{{ else }}https://{{ .Values.global.restApiSubdomain }}.{{ .Values.global.domain }}/idp{{ end }}
              {{- end }}
              {{- if .Values.api.oauth.secretRef }}
            - name: OAUTH_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  key: OAUTH_REDIRECT_URI
                  name: {{ .Values.api.oauth.secretRef }}
              {{- else }}
            - name: OAUTH_REDIRECT_URI
              value: "{{ if .Values.api.oauth.redirectUri }}{{ .Values.api.oauth.redirectUri }}{{ else }}https://{{ .Values.global.restApiSubdomain }}.{{ .Values.global.domain }}/auth/callback{{ end }}"
              {{- end }}
            - name: NATS_URI
              value: {{ .Values.api.nats.uri }}
            {{- $dashboardAddress := "" }}
            {{- if .Values.api.dashboardAddress }}
            {{- $dashboardAddress = .Values.api.dashboardAddress }}
            {{- else if .Values.api.redirectSubdomain }}
            {{- $dashboardAddress = printf "https://%s.%s" .Values.api.redirectSubdomain .Values.global.domain }}
            {{- else }}
            {{- $dashboardAddress = printf "https://%s.%s" .Values.global.uiSubdomain .Values.global.domain }}
            {{- end }}
            - name: ALLOWED_EXTERNAL_REDIRECT_URIS
              value: {{ if .Values.api.oauth.allowedExternalRedirectURIs }}{{ .Values.api.oauth.allowedExternalRedirectURIs }}{{ else }}{{ $dashboardAddress }}{{ end }}
            {{- if .Values.api.agent.hide }}
            - name: HIDE_AGENT_HOST
              value: "{{ .Values.api.agent.hide }}"
            {{- end }}
            - name: AGENT_HOST
              value: {{ if .Values.api.agent.host }}{{ .Values.api.agent.host }}{{ else }}{{ .Values.global.grpcApiSubdomain }}.{{ .Values.global.domain }}{{ end }}
            - name: AGENT_PORT
              value: "{{ .Values.api.agent.port }}"
            - name: API_ADDRESS
              value: {{ if .Values.api.apiAddress }}{{ .Values.api.apiAddress }}{{ else }}https://{{ .Values.global.restApiSubdomain }}.{{ .Values.global.domain }}{{ end }}
            - name: DASHBOARD_ADDRESS
              value: {{ $dashboardAddress }}
            - name: USE_TLS
              value: "{{ .Values.api.tls.serveHTTPS }}"
            - name: TLS_CERT
              value: "{{ .Values.api.tls.certPath }}"
            - name: TLS_KEY
              value: "{{ .Values.api.tls.keyPath }}"
            {{- if .Values.global.customCaSecretRef }}
            - name: SSL_CERT_DIR
              value: /etc/testkube/certs
            {{- end }}
            - name: OUTPUTS_BUCKET
              value: "{{ .Values.api.outputsBucket }}"
            - name: MINIO_ENDPOINT
              value: "{{ tpl .Values.api.minio.endpoint . }}"
            - name: MINIO_REGION
              value: "{{ .Values.api.minio.region }}"
            - name: MINIO_SSL
              value: "{{ .Values.api.minio.secure }}"
            - name: MINIO_EXPIRATION
              value: "{{ .Values.api.minio.expirationPeriod }}"
            - name: MINIO_ACCESS_KEY_ID
              {{- if .Values.api.minio.credsSecretRef }}
              valueFrom:
                secretKeyRef:
                  key: root-user
                  name: {{ .Values.api.minio.credsSecretRef }}
              {{- else }}
              value: "{{ .Values.api.minio.accessKeyId }}"
              {{- end }}
            - name: MINIO_SECRET_ACCESS_KEY
              {{- if .Values.api.minio.credsSecretRef }}
              valueFrom:
                secretKeyRef:
                  key: root-password
                  name: {{ .Values.api.minio.credsSecretRef }}
              {{- else }}
              value: "{{ .Values.api.minio.secretAccessKey }}"
              {{- end }}
            - name: MINIO_TOKEN
              {{- if .Values.api.minio.credsSecretRef }}
              valueFrom:
                secretKeyRef:
                  key: token
                  name: {{ .Values.api.minio.credsSecretRef }}
              {{- else }}
              value: "{{ .Values.api.minio.token }}"
              {{- end }}
            - name: "MINIO_SKIP_VERIFY"
              value: "{{ .Values.api.minio.skipVerify }}"
            {{- if .Values.api.minio.certSecret.enabled }}
            - name: "MINIO_CERT_FILE"
              value: "{{ .Values.api.minio.certSecret.baseMountPath }}/{{ .Values.api.minio.certSecret.certFile }}"
            - name: "MINIO_KEY_FILE"
              value: "{{ .Values.api.minio.certSecret.baseMountPath }}/{{ .Values.api.minio.certSecret.keyFile }}"
            {{- if .Values.api.minio.mountCACertificate }}
            - name: "MINIO_CA_FILE"
              value: "{{ .Values.api.minio.certSecret.baseMountPath }}/{{ .Values.api.minio.certSecret.caFile }}"
            {{- end }}
            {{- end }}
            {{- if .Values.api.features.disablePersonalOrgs }}
            - name: "DISABLE_PERSONAL_ORGS"
              value: "{{.Values.api.features.disablePersonalOrgs }}"
            {{- end }}
            {{- if or .Values.api.features.bootstrapConfig.enabled .Values.api.features.bootstrapOrg }}
            - name: "BOOTSTRAP_CONFIG_ENABLED"
              value: "true"
            - name: "BOOTSTRAP_CONFIG_PATH"
              value: "/app/config/config"
            {{- end}}
            {{- with .Values.api.features.bootstrapAgentTokenSecretRef }}
            - name: {{ snakecase . | upper | quote }}
              valueFrom:
                secretKeyRef: 
                  name: {{ . | quote}}
                  key: agent-token
            {{- end}}
            {{- range $k, $v := .Values.additionalEnv }}
            - name: {{ $k }}
              value: {{ tpl ($v | toString) $ | quote }}
            {{- end}}
            {{- if .Values.externalSecrets.enabled -}}
            {{- range $key, $value := .Values.externalSecrets.keys }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  key: {{ $value }}
                  name: api-external-secrets
            {{ end }}
            {{- end}}
          ports:
            - name: {{ if .Values.api.tls.serveHTTPS }}https{{ else }}http{{ end }}
              containerPort: {{ if .Values.api.tls.serveHTTPS }}{{ .Values.api.tls.apiPort }}{{ else }}8090{{ end }}
              protocol: TCP
            - name: {{ if .Values.api.tls.serveHTTPS }}grpcs{{ else }}grpc{{ end }}
              containerPort: {{ if .Values.api.tls.serveHTTPS }}{{ .Values.api.tls.agentPort }}{{ else }}8089{{ end }}
              protocol: TCP
            {{- if .Values.prometheus.enabled }}
            - name: metrics
              containerPort: 9100
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              scheme: {{ if .Values.api.tls.serveHTTPS }}HTTPS{{ else }}HTTP{{ end }}
              port: {{ if .Values.api.tls.serveHTTPS }}https{{ else }}http{{ end }}
          readinessProbe:
            httpGet:
              path: /health
              scheme: {{ if .Values.api.tls.serveHTTPS }}HTTPS{{ else }}HTTP{{ end }}
              port: {{ if .Values.api.tls.serveHTTPS }}https{{ else }}http{{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.api.tls.serveHTTPS .Values.global.enterpriseLicenseSecretRef .Values.global.customCaSecretRef .Values.api.features.bootstrapConfig.enabled .Values.api.features.bootstrapOrg }}
          volumeMounts:
            {{- if .Values.api.tls.serveHTTPS }}
            - mountPath: /tmp/serving-cert/crt.pem
              readOnly: true
              name: serving-cert
              subPath: tls.crt
            - mountPath: /tmp/serving-cert/key.pem
              readOnly: true
              name: serving-cert
              subPath: tls.key
            {{- end }}
            {{- if and .Values.global.enterpriseLicenseSecretRef .Values.global.enterpriseOfflineAccess }}
            - mountPath: /testkube/license.lic
              readOnly: true
              name: license-file
              subPath: license.lic
            {{- end }}
            {{- if .Values.global.customCaSecretRef }}
            - mountPath: /etc/testkube/certs/testkube-custom-ca.pem
              name: {{ .Values.global.customCaSecretRef }}
              readOnly: true
              subPath: ca.crt
            {{- end }}
            {{- if or .Values.api.features.bootstrapConfig.enabled .Values.api.features.bootstrapOrg }}
            - mountPath: /app/config
              name: testkube-config
            {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.api.tls.serveHTTPS .Values.global.enterpriseLicenseSecretRef .Values.global.customCaSecretRef .Values.api.features.bootstrapConfig.enabled .Values.api.features.bootstrapOrg }}
      volumes:
        {{- if .Values.api.tls.serveHTTPS }}
        - name: serving-cert
          secret:
            secretName: {{ .Values.api.tls.tlsSecret }}
        {{- end }}
        {{- if and .Values.global.enterpriseLicenseSecretRef .Values.global.enterpriseOfflineAccess }}
        - name: license-file
          secret:
            secretName: {{ .Values.global.enterpriseLicenseSecretRef }}
        {{- end }}
        {{- if .Values.global.customCaSecretRef }}
        - name: {{ .Values.global.customCaSecretRef }}
          secret:
            secretName: {{ .Values.global.customCaSecretRef }}
            defaultMode: 420
        {{- end }}
        {{- if or .Values.api.features.bootstrapConfig.enabled .Values.api.features.bootstrapOrg }}
        - configMap:
            defaultMode: 420
            name: {{ include "testkube-cloud-api.fullname" . }}-config
          name: testkube-config
        {{- end }}
      {{- end }}
