apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "testkube-cloud-api.fullname" . }}
  labels:
    {{- include "testkube-cloud-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "testkube-cloud-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "testkube-cloud-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "testkube-cloud-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PAYMENTS_PORTAL_CONFIGURATION_ID
            {{- if .Values.payments.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: PAYMENTS_PORTAL_CONFIGURATION_ID
                  name: {{ .Values.payments.secretRef }}
            {{- else }}
              value: {{ .Values.payments.portalConfigurationId }}
            {{- end }}
            - name: PAYMENTS_ENDPOINT_SECRET
            {{- if .Values.payments.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: PAYMENTS_ENDPOINT_SECRET
                  name: {{ .Values.payments.secretRef }}
            {{- else }}
              value: {{ .Values.payments.endpointSecret }}
            {{- end }}
            - name: PAYMENTS_API_KEY
            {{- if .Values.payments.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: PAYMENTS_API_KEY
                  name: {{ .Values.payments.secretRef }}
            {{- else }}
              value: {{ .Values.payments.apiKey }}
            {{- end }}
            - name: SEGMENTIO_WRITE_KEY
            {{- if .Values.analytics.segmentio.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: SEGMENTIO_WRITE_KEY
                  name: {{ .Values.analytics.segmentio.secretRef }}
            {{- else }}
              value: {{ .Values.analytics.segmentio.writeKey }}
            {{- end }}
            - name: SENDGRID_API_KEY
            {{- if .Values.api.sendgrid.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: SENDGRID_API_KEY
                  name: {{ .Values.api.sendgrid.secretRef }}
            {{- else }}
              value: {{ .Values.api.sendgrid.apiKey }}
            {{- end }}
            - name: API_MONGO_DSN
            {{- if .Values.api.mongoDsnSecretRef }}
              valueFrom:
                secretKeyRef:
                  key: MONGO_DSN
                  name: {{ .Values.api.mongoDsnSecretRef }}
            {{- else }}
              value: {{ .Values.api.mongoDsn }}
            {{- end }}
            - name: API_MONGO_DB
              value: {{ .Values.api.mongoDb }}
            {{- if .Values.api.oauth.secretRef }}
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: OAUTH_CLIENT_ID
                  name: {{ .Values.api.oauth.secretRef }}
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: OAUTH_CLIENT_SECRET
                  name: {{ .Values.api.oauth.secretRef }}
            - name: OAUTH_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  key: OAUTH_ISSUER_URL
                  name: {{ .Values.api.oauth.secretRef }}
            - name: OAUTH_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  key: OAUTH_REDIRECT_URI
                  name: {{ .Values.api.oauth.secretRef }}
            {{- end }}
            {{- if .Values.api.oauth.clientId }}
            - name: OAUTH_CLIENT_ID
              value: {{ .Values.api.oauth.clientId }}
            {{- end }}
            {{- if .Values.api.oauth.clientSecret }}
            - name: OAUTH_CLIENT_SECRET
              value: {{ .Values.api.oauth.clientSecret }}
            {{- end }}
            {{- if .Values.api.oauth.issuerUrl }}
            - name: OAUTH_ISSUER_URL
              value: {{ .Values.api.oauth.issuerUrl }}
            {{- end }}
            {{- if .Values.api.oauth.redirectUri }}
            - name: OAUTH_REDIRECT_URI
              value: {{ .Values.api.oauth.redirectUri }}
            {{- end }}
            - name: NATS_URI
              value: {{ .Values.api.natsUri }}
            - name: ALLOWED_EXTERNAL_REDIRECT_URIS
              value: {{ .Values.api.oauth.allowedExternalRedirectURIs }}
            {{- if .Values.api.agent.hide }}
            - name: HIDE_AGENT_HOST
              value: "{{ .Values.api.agent.hide }}"
            {{- end }}
            - name: AGENT_HOST
              value: "{{ .Values.api.agent.host }}"
            - name: AGENT_PORT
              value: "{{ .Values.api.agent.port }}"
            - name: API_ADDRESS
              value: "{{ .Values.api.apiAddress }}"
            - name: DASHBOARD_ADDRESS
              value: "{{ .Values.api.dashboardAddress }}"
            - name: USE_TLS
              value: "{{ .Values.api.tls.enabled }}"
            - name: TLS_CERT
              value: "{{ .Values.api.tls.certPath }}"
            - name: TLS_KEY
              value: "{{ .Values.api.tls.keyPath }}"
            - name: OUTPUTS_BUCKET
              value: "{{ .Values.api.outputsBucket }}"
            {{- range $k, $v := .Values.additionalEnv }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end}}
          ports:
            {{- if .Values.api.tls.enabled }}
            - name: https
              containerPort: {{ .Values.api.tls.apiPort }}
              protocol: TCP
            {{- else }}
            - name: http
              containerPort: 8090
              protocol: TCP
            {{- end }}
            {{- if .Values.prometheus.enabled }}
            - name: metrics
              containerPort: 9000
              protocol: TCP
            {{- end }}
            {{- if .Values.api.tls.enabled }}
            - name: grpcs
              containerPort:  {{ .Values.api.tls.agentPort }}
              protocol: TCP
            {{- else }}
            - name: grpc
              containerPort: 8089
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              scheme: {{ if .Values.api.tls.enabled }}HTTPS{{ else }}HTTP{{ end }}
              port: {{ if .Values.api.tls.enabled }}https{{ else }}http{{ end }}
          readinessProbe:
            httpGet:
              path: /health
              scheme: {{ if .Values.api.tls.enabled }}HTTPS{{ else }}HTTP{{ end }}
              port: {{ if .Values.api.tls.enabled }}https{{ else }}http{{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.api.tls.enabled }}
          volumeMounts:
            - mountPath: /tmp/serving-cert/crt.pem
              readOnly: true
              name: serving-cert
              subPath: tls.crt
            - mountPath: /tmp/serving-cert/key.pem
              readOnly: true
              name: serving-cert
              subPath: tls.key
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.api.tls.enabled }}
      volumes:
        - name: serving-cert
          secret:
            secretName: {{ .Values.api.tls.tlsSecret }}
      {{- end }}