{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: testkube-cloud-api-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: gcp-store
  target:
    name: testkube-cloud-api-secrets
    creationPolicy: Owner
  {{- if .Values.externalSecrets.secrets }}
  data:
    {{- range $key, $value := .Values.externalSecrets.secrets }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $value }}
    {{- end }}
  {{- end }}
{{- end }}
