{{- if .Values.api.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    {{- include "testkube-cloud-api.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.api.migrations.useHelmHooks }}
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    {{- end }}
  name: {{ include "testkube-cloud-api.fullname" . }}-migrations
spec:
  {{- if .Values.api.migrations.ttlSecondsAfterFinished  }}
  ttlSecondsAfterFinished: {{ .Values.api.migrations.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        {{- if hasKey . "vault.hashicorp.com/agent-inject" }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        {{- end }}
      {{- end }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- else if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "testkube-cloud-api.serviceAccountName" . }}
      securityContext: {{ include "testkube-cloud-api.podSecurityContext" . | nindent 8 }}
      containers:
        - name: migrations
          image: {{ include "testkube-migration.image" . }}
          securityContext: {{ include "testkube-cloud-api.containerSecurityContext" . | nindent 12 }}
          env:
            - name: ENTERPRISE_MODE
              value: "{{ .Values.global.enterpriseMode }}"
            {{- if .Values.payments.enabled }}
            - name: PAYMENTS_API_KEY
              {{- if .Values.payments.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: PAYMENTS_API_KEY
                  name: {{ .Values.payments.secretRef }}
              {{- else }}
              value: {{ .Values.payments.apiKey }}
              {{- end }}
            {{- end }}
            - name: API_MONGO_DSN
              {{- if .Values.api.mongo.dsnSecretRef }}
              valueFrom:
                secretKeyRef:
                  key: MONGO_DSN
                  name: {{ .Values.api.mongo.dsnSecretRef }}
              {{- else }}
              value: {{ .Values.api.mongo.dsn }}
              {{- end }}
            - name: API_MONGO_DB
              value: {{ .Values.api.mongo.database }}
            - name: MIGRATION_IGNORE_NO_DB_ERROR
              value: {{ .Values.api.migrations.ignoreNoDbError }}
      restartPolicy: Never
  backoffLimit: 3
{{- end }}
