{{- if .Values.api.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "testkube-cloud-api.migration-jobname" . }}
  labels:
    {{- include "testkube-cloud-api.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.api.migrations.useArgoHooks }}
      "argocd.argoproj.io/hook": "Sync"
      "argocd.argoproj.io/hook-delete-policy": "BeforeHookCreation"
    {{- end }}
spec:
  {{- if .Values.api.migrations.ttlSecondsAfterFinished  }}
  ttlSecondsAfterFinished: {{ .Values.api.migrations.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        {{- if hasKey . "vault.hashicorp.com/agent-inject" }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        {{- end }}
      {{- end }}
    spec:
      {{- with (default .Values.imagePullSecrets .Values.global.imagePullSecrets) }}
      imagePullSecrets:
        {{- range . }}
        {{- if typeIsLike "map[string]interface {}" . }}
      - name: {{ .name | quote }}
        {{- else }}
      - name: {{ . | quote  }}
        {{- end }}
        {{- end }}
        {{- end }}
      serviceAccountName: {{ include "testkube-cloud-api.serviceAccountName" . }}
      securityContext: {{ include "testkube-cloud-api.podSecurityContext" . | nindent 8 }}
      containers:
        - name: migrations
          image: {{ include "testkube-migration.image" . }}
          imagePullPolicy: {{ .Values.migrationImage.pullPolicy }}
          securityContext: {{ include "testkube-cloud-api.containerSecurityContext" . | nindent 12 }}
          env:
            - name: ENTERPRISE_MODE
              value: "{{ .Values.global.enterpriseMode }}"
            {{- if .Values.payments.enabled }}
            - name: PAYMENTS_API_KEY
              {{- if .Values.payments.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: PAYMENTS_API_KEY
                  name: {{ .Values.payments.secretRef }}
              {{- else }}
              value: {{ .Values.payments.apiKey }}
              {{- end }}
            {{- end }}
            {{- $mongoDsnSecretRef := .Values.global.mongo.dsnSecretRef | default .Values.api.mongo.dsnSecretRef }}
            {{- $mongoDsn := .Values.global.mongo.dsn | default .Values.api.mongo.dsn }}
            {{- if $mongoDsnSecretRef }}
            - name: API_MONGO_DSN
              valueFrom:
                secretKeyRef:
                  key: MONGO_DSN
                  name: {{ $mongoDsnSecretRef }}
            {{- else if $mongoDsn }}
            - name: API_MONGO_DSN
              value: {{ $mongoDsn }}
            {{- end }}
            {{- $mongoDatabase := .Values.global.mongo.database | default .Values.api.mongo.database }}
            - name: API_MONGO_DB
              value: {{ $mongoDatabase }}
            {{- $mongoReadPreference := .Values.global.mongo.readPreference | default .Values.api.mongo.readPreference }}
            - name: API_MONGO_READ_PREFERENCE
              value: {{ $mongoReadPreference }}
            - name: MIGRATION_IGNORE_NO_DB_ERROR
              value: "{{ .Values.api.migrations.ignoreNoDbError }}"
            - name: MIGRATION_MIGRATE_DATABASE
              value: "true"
            - name: MIGRATION_INIT_INDEXES
              value: "true"
            {{- if or .Values.global.customCaSecretRef .Values.customCaDirPath }}
            {{- $certsDir := .Values.customCaDirPath | default "/etc/testkube/certs" }}
            - name: SSL_CERT_DIR
              value: "{{ $certsDir }}"
            {{- end }}
          {{- if .Values.global.customCaSecretRef }}
          volumeMounts:
            {{- $certsDir := .Values.customCaDirPath | default "/etc/testkube/certs" }}
            - mountPath: {{ $certsDir }}/testkube-custom-ca.pem
              name: {{ .Values.global.customCaSecretRef }}
              readOnly: true
              subPath: {{ .Values.global.customCaSecretKey }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.global.customCaSecretRef }}
      volumes:
        - name: {{ .Values.global.customCaSecretRef }}
          secret:
            secretName: {{ .Values.global.customCaSecretRef }}
            defaultMode: 420
      {{- end }}
      restartPolicy: Never
  backoffLimit: 3
{{- end }}
