{{- if .Values.api.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
  name: {{ include "testkube-cloud-api.fullname" . }}-migrations
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: migrations
          image: {{ .Values.api.migrations.image.repository }}:{{ .Values.image.tag }}
          args:
            - up
          env:
            - name: MONGO_URL
            {{- if .Values.api.mongoDsnSecretRef }}
              valueFrom:
                secretKeyRef:
                  key: MONGO_DSN
                  name: {{ .Values.api.mongoDsnSecretRef }}
            {{- else }}
              value: {{ .Values.api.mongoDsn }}
            {{- end }}
            - name: MONGO_DB
              value: {{ .Values.api.mongoDb }}
      restartPolicy: Never
  backoffLimit: 3
{{- end }}