{{- if .Values.api.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "testkube-cloud-api.migration-jobname" . }}
  labels:
    {{- include "testkube-cloud-api.labels" . | nindent 4 }}
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: {{ .Values.api.migrations.ttlSecondsAfterFinished }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        {{- if hasKey . "vault.hashicorp.com/agent-inject" }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        {{- end }}
      {{- end }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- else if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "testkube-cloud-api.serviceAccountName" . }}
      securityContext: {{ include "testkube-cloud-api.podSecurityContext" . | nindent 8 }}
      containers:
        - name: migrations
          image: {{ include "testkube-cloud-api.toolbox-image" . }}
          imagePullPolicy: {{ .Values.toolboxImage.pullPolicy }}
          command: ["/testkube/toolbox"]
          args: ["database", "migrations", "up"]
          securityContext: {{ include "testkube-cloud-api.containerSecurityContext" . | nindent 12 }}
          env:
            - name: ENTERPRISE_MODE
              value: "{{ .Values.global.enterpriseMode }}"
            {{- if .Values.payments.enabled }}
            - name: PAYMENTS_API_KEY
              {{- if .Values.payments.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: PAYMENTS_API_KEY
                  name: {{ .Values.payments.secretRef }}
              {{- else }}
              value: {{ .Values.payments.apiKey }}
              {{- end }}
            {{- end }}
            {{- $mongoDsnSecretRef := .Values.global.mongo.dsnSecretRef | default .Values.api.mongo.dsnSecretRef }}
            {{- $mongoDsn := .Values.global.mongo.dsn | default .Values.api.mongo.dsn }}
            {{- if $mongoDsnSecretRef }}
            - name: API_MONGO_DSN
              valueFrom:
                secretKeyRef:
                  key: MONGO_DSN
                  name: {{ $mongoDsnSecretRef }}
            {{- else if $mongoDsn }}
            - name: API_MONGO_DSN
              value: {{ $mongoDsn }}
            {{- end }}
            {{- $mongoDatabase := .Values.global.mongo.database | default .Values.api.mongo.database }}
            - name: API_MONGO_DB
              value: {{ $mongoDatabase }}
            - name: MIGRATION_IGNORE_NO_DB_ERROR
              value: "{{ .Values.api.migrations.ignoreNoDbError }}"
            - name: MIGRATION_INIT_INDEXES
              value: "true"
            - name: MIGRATION_MIGRATE_DATABASE
              value: "true"
            - name: HELLO
              value: "world"
      restartPolicy: Never
{{- end }}
