{{- if .Values.api.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    {{- include "testkube-cloud-api.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.api.migrations.useHelmHooks }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    {{- end }}
  name: {{ include "testkube-cloud-api.fullname" . }}-migrations
spec:
  {{- if .Values.api.migrations.ttlSecondsAfterFinished  }}
  ttlSecondsAfterFinished: {{ .Values.api.migrations.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- if hasKey .Values.podAnnotations "vault.hashicorp.com/agent-inject" }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
      {{- end }}
      {{- end }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- else if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "testkube-cloud-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args: ["migrate"]
          env:
            - name: ENTERPRISE_MODE
              value: "{{ .Values.global.enterpriseMode }}"
            {{- if .Values.global.enterpriseMode }}
            - name: ENTERPRISE_OFFLINE_ACTIVATION
              value: "{{ .Values.global.enterpriseOfflineAccess }}"
            - name: ENTERPRISE_LICENSE_KEY_PATH
              value: "{{ .Values.enterpriseLicenseKeyPath }}"
            - name: ENTERPRISE_LICENSE_FILE_PATH
              value: "{{ .Values.enterpriseLicenseFilePath }}"
            {{ if or .Values.global.enterpriseLicenseSecretRef .Values.global.enterpriseLicenseKey }}
            - name: ENTERPRISE_LICENSE_KEY
              {{- if .Values.global.enterpriseLicenseSecretRef }}
              valueFrom:
                secretKeyRef:
                  key: LICENSE_KEY
                  name: {{ .Values.global.enterpriseLicenseSecretRef }}
              {{- else }}
              value: "{{ .Values.global.enterpriseLicenseKey }}"
              {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.global.enterpriseLicenseFile }}
            - name: ENTERPRISE_LICENSE_FILE
              value: "{{ .Values.global.enterpriseLicenseFile }}"
            {{- end }}
            {{- if .Values.payments.enabled }}
            - name: PAYMENTS_PORTAL_CONFIGURATION_ID
              {{- if .Values.payments.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: PAYMENTS_PORTAL_CONFIGURATION_ID
                  name: {{ .Values.payments.secretRef }}
              {{- else }}
              value: {{ .Values.payments.portalConfigurationId }}
              {{- end }}
            - name: PAYMENTS_ENDPOINT_SECRET
              {{- if .Values.payments.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: PAYMENTS_ENDPOINT_SECRET
                  name: {{ .Values.payments.secretRef }}
              {{- else }}
              value: {{ .Values.payments.endpointSecret }}
              {{- end }}
            - name: PAYMENTS_API_KEY
              {{- if .Values.payments.secretRef }}
              valueFrom:
                secretKeyRef:
                  key: PAYMENTS_API_KEY
                  name: {{ .Values.payments.secretRef }}
              {{- else }}
              value: {{ .Values.payments.apiKey }}
              {{- end }}
            {{- end }}
            - name: API_MONGO_DSN
              {{- if .Values.api.mongo.dsnSecretRef }}
              valueFrom:
                secretKeyRef:
                  key: MONGO_DSN
                  name: {{ .Values.api.mongo.dsnSecretRef }}
              {{- else }}
              value: {{ .Values.api.mongo.dsn }}
              {{- end }}
            - name: API_MONGO_DB
              value: {{ .Values.api.mongo.database }}
          {{- if and .Values.global.enterpriseLicenseSecretRef .Values.global.enterpriseOfflineAccess }}
          volumeMounts:
            - mountPath: {{ .Values.global.enterpriseLicenseFilePath }}
              readOnly: true
              name: license-file
              subPath: license.lic
          {{- end }}
      {{- if and .Values.global.enterpriseLicenseSecretRef .Values.global.enterpriseOfflineAccess }}
      volumes:
        - name: license-file
          secret:
            secretName: {{ .Values.global.enterpriseLicenseSecretRef }}
      {{- end }}
      restartPolicy: Never
  backoffLimit: 3
{{- end }}
