{{- if .Values.api.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    {{- include "testkube-cloud-api.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.api.migrations.useHelmHooks }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    {{- end }}
  name: {{ include "testkube-cloud-api.fullname" . }}-migrations
spec:
  template:
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- else if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["/testkube/cloud-api"]
          args: ["migrate"]
          env: []
            
            # {{ include "testkube-cloud-api.env" . nindent 12 }} /* include values from _helpers.tpl */
      restartPolicy: Never
  backoffLimit: 3
{{- end }}