{{- if .Values.minio.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "testkube-cloud-api.minio.fullname" . }}-pvc
  labels:
    {{- include "testkube-cloud-api.minio.labels" . | nindent 4 }}
spec:
  {{- if .Values.minio.storageClassName }}
  storageClassName: {{ .Values.minio.storageClassName }}
  {{- end }}
  accessModes:
  {{- range .Values.minio.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.minio.persistence.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "testkube-cloud-api.minio.fullname" . }}
  labels:
    {{- include "testkube-cloud-api.minio.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "testkube-cloud-api.minio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "testkube-cloud-api.minio.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: minio
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          args:
            - server
            - /data
            - --console-address
            - ":9090"
          env:
            - name: MINIO_ROOT_USER
              {{- if .Values.minio.credentials.secretRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.credentials.secretRef }}
                  key: ACCESS_KEY_ID
              {{- else }}
              value: "{{ .Values.minio.credentials.accessKeyId }}"
              {{- end }}
            - name: MINIO_ROOT_PASSWORD
              {{- if .Values.minio.credentials.secretRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.credentials.secretRef }}
                  key: SECRET_ACCESS_KEY
              {{- else }}
              value: "{{ .Values.minio.credentials.secretAccessKey }}"
              {{- end }}
            - name: CONSOLE_PORT
              value: "9090"
            - name: CONSOLE_TLS_PORT
              value: "9443"
            {{- with .Values.minio.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 9000
              name: http
            - containerPort: 9090
              name: web
            - containerPort: 9443
              name: https
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
          volumeMounts:
            - name: minio-data
              mountPath: "/data"
          {{- with .Values.minio.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.minio.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: {{ include "testkube-cloud-api.minio.fullname" . }}-pvc
      {{- with .Values.minio.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end}}
      serviceAccountName: {{ include "testkube-cloud-api.minio.findServiceAccountName" . }}
      {{- with .Values.minio.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.minio.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.minio.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "testkube-cloud-api.minio.fullname" . }}
  labels:
    {{- include "testkube-cloud-api.minio.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      protocol: TCP
    - name: web
      port: 9090
      protocol: TCP
    - name: https
      port: 9443
      protocol: TCP
  selector:
    {{- include "testkube-cloud-api.minio.selectorLabels" . | nindent 4 }}
---
{{- if .Values.minio.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.minio.serviceAccount.labels }}
  labels:
      {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.minio.serviceAccount.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.minio.serviceAccount.name | quote }}
{{- end }}
{{- end }}
