{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "testkube-cloud-api.fullname" . }}-gcp-store
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcp.projectId }}
{{- end }}