{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "testkube-cloud-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "testkube-cloud-api.labels" . | nindent 4 -}}
    {{- with .Values.prometheus.labels }}
    {{- toYaml . | nindent 4 -}}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "testkube-cloud-api.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.prometheus.port }}
      path: {{ .Values.prometheus.path }}
      interval: {{ .Values.prometheus.scrapeInterval }}
{{- end }}

