apiVersion: v1
kind: Service
metadata:
  name: {{ include "testkube-cloud-api.fullname" . }}
  labels:
    {{- include "testkube-cloud-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.api.tls.enabled }}
    - port: {{ .Values.api.tls.apiPort }}
      targetPort: https
      protocol: TCP
      name: https
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
    {{- if .Values.api.tls.enabled }}
    - port: {{ .Values.api.tls.agentPort }}
      targetPort: grpcs
      protocol: TCP
      name: grpcs
    {{- else }}
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end }}
    {{- if .Values.prometheus.enabled }}
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "testkube-cloud-api.selectorLabels" . | nindent 4 }}
