apiVersion: v1
kind: Service
metadata:
  name: {{ include "testkube-cloud-api.fullname" . }}
  labels:
    {{- include "testkube-cloud-api.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ if .Values.api.tls.serveHTTPS }}{{ .Values.api.tls.apiPort }}{{ else }}{{ .Values.service.port }}{{ end }}
      targetPort: {{ if .Values.api.tls.serveHTTPS }}https{{ else }}http{{ end }}
      protocol: TCP
      name: {{ if .Values.api.tls.serveHTTPS }}https{{ else }}http{{ end }}
    - port: {{ if .Values.api.tls.serveHTTPS }}{{ .Values.api.tls.agentPort }}{{ else }}{{ .Values.service.grpcPort }}{{ end }}
      targetPort: {{ if .Values.api.tls.serveHTTPS }}grpcs{{ else }}grpc{{ end }}
      protocol: TCP
      name: {{ if .Values.api.tls.serveHTTPS }}grpcs{{ else }}grpc{{ end }}
    {{- if .Values.prometheus.enabled }}
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "testkube-cloud-api.selectorLabels" . | nindent 4 }}
