apiVersion: v2
type: application
name: dex
version: 0.19.1-7
appVersion: "2.42.0"
kubeVersion: ">=1.14.0-0"
description: OpenID Connect (OIDC) identity and OAuth 2.0 provider with pluggable connectors.
icon: https://dexidp.io/favicon.png
keywords:
  - oidc
  - oauth
  - identity-provider
  - saml
home: https://dexidp.io/
sources:
  - https://github.com/dexidp/dex
  - https://github.com/dexidp/helm-charts/tree/master/charts/dex
maintainers:
  - name: sagikazarmark
    email: mark.sagikazar@gmail.com
    url: https://sagikazarmark.hu
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: "Fixed reference to global.imageRegistry"
  artifacthub.io/images: |
    - name: dex
      image: docker.io/kubeshop/dex:v2.42.0
