{{- include "nats.defaultValues" . }}
{{- if or .Values.global.podDisruptionBudget.enabled .Values.podDisruptionBudget.enabled }}
{{- with .Values.podDisruptionBudget }}
{{- include "nats.loadMergePatch" (merge (dict "file" "pod-disruption-budget.yaml" "ctx" $) .) }}
{{- end }}
{{- end }}
