apiVersion: v2
name: testkube-migrations
description: A Helm chart for migrations of Testkube MongoDB
type: application
version: 0.1.0
appVersion: 0.1.0
maintainers:
  - name: testkube
    url: https://testkube.io
icon: https://assets.website-files.com/61e00b3936e571a4ea7a5a4c/623b2bb9387ad04955b1f82c_testkube.svg
home: https://github.com/kubeshop/testkube-cloud-charts
