
imagePullSecrets:
  - name: testkube-cloud-creds

api:
  migrations:
    enabled: true
  tls:
    enabled: true
    issuerRef: letsencrypt-dev
    domains:
      - api.testkube.xyz
      - agent.testkube.xyz
  agent:
    hide: false
    host: api.testkube.xyz
    port: 443
  apiAddress: https://api.testkube.xyz
  dashboardAddress: https://cloud.testkube.xyz
  natsUri: "nats://nats.messaging.svc.cluster.local:4222"
  sendgrid:
    secretRef: sendgrid-api-key
  oauth:
    secretRef: testkube-cloud-oauth-secret
    allowedExternalRedirectURIs: https://cloud.testkube.xyz,https://*-testkube-cloud.vercel.app,http://localhost:3000

prometheus:
  enabled: true

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/limit-rps: "5"
    nginx.ingress.kubernetes.io/limit-rpm: "300"
    nginx.ingress.kubernetes.io/limit-connections: "10"

    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
  hosts:
    - host: api.testkube.xyz
      paths:
        - path: /
          pathType: Prefix
          svcPort: 9443
grpcIngress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: GRPCS
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/client-header-timeout: "10800"
    nginx.ingress.kubernetes.io/client-body-timeout: "10800"
    nginx.ingress.kubernetes.io/limit-rps: "100"
    nginx.ingress.kubernetes.io/limit-rpm: "500"
    nginx.ingress.kubernetes.io/limit-connections: "500"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
  hosts:
    - host: agent.testkube.xyz
      paths:
        - path: /
          pathType: Prefix
          svcPort: 8443
  tls:
    - secretName: testkube-cloud-api-tls
      hosts:
        - agent.testkube.xyz
serviceAccount:
  create: true

autoscaling:
  enabled: false
  minReplicas: 3