global:
  domain: testkube.xyz
  certificateProvider: cert-manager
  certManager:
    issuerRef: letsencrypt-dev

imagePullSecrets:
  - name: testkube-cloud-creds

additionalEnv:
  TEST_TOKENS_ENABLED: "true"

analytics:
  segmentio:
    enabled: true
    secretRef: testkube-cloud-analytics-secret

payments:
  enabled: true
  secretRef: testkube-cloud-payments-secret

api:
  migrations:
    enabled: true
  tls:
    enabled: true
  mongo:
    dsnSecretRef: "mongo-dsn"
  nats:
    uri: "nats://nats.messaging.svc.cluster.local:4222"
  sendgrid:
    secretRef: sendgrid-api-key
  oauth:
    secretRef: testkube-cloud-oauth-secret

serviceAccount:
  create: true
  annotations:
    gcpServiceAccount: "testkube-cloud-api@testkube-328312.iam.gserviceaccount.com"

prometheus:
  enabled: true

resources:
  requests:
    cpu: 150m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1000Mi

autoscaling:
  enabled: true
  minReplicas: 3

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - testkube-cloud-api
          topologyKey: kubernetes.io/hostname