{{- if .Values.dex.configSecret.createCustom }}
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ .Values.dex.configSecret.name }}
  labels:
    {{- include "testkube-enterprise.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  {{- if .Values.dex.configTemplate.customConfig }}
  config.yaml: |-
    {{- .Values.dex.configTemplate.customConfig | nindent 4 }}
  {{- else }}
  config.yaml: |-
    {{- .Values.dex.configTemplate.base | nindent 4 }}
    issuer: https://{{ .Values.global.restApiSubdomain }}.{{ .Values.global.domain }}/idp
    staticClients:
      {{- $api := index .Values "testkube-cloud-api" }}
      - id: {{ $api.api.oauth.clientId }}
        name: 'Testkube Enterprise'
        secret: '{{ $api.api.oauth.clientSecret }}'
        redirectURIs:
          - 'https://{{ .Values.global.restApiSubdomain }}.{{ .Values.global.domain }}/auth/callback'
    {{- if .Values.dex.configTemplate.additionalConfig }}
    {{ .Values.dex.configTemplate.additionalConfig | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}