{{- if .Values.dex.configSecret.createCustom }}
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ .Values.dex.configSecret.name }}
  labels:
    {{- include "testkube-enterprise.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  {{- if .Values.dex.configTemplate.customConfig }}
  config.yaml: |-
    {{- .Values.dex.configTemplate.customConfig | nindent 4 }}
  {{- else }}
  config.yaml: |-
    {{- .Values.dex.configTemplate.base | nindent 4 }}
    storage:
      {{- with .Values.dex.storage }}
      {{- toYaml . | nindent 6 }}
      {{- else }}
        type: kubernetes
        config:
          inCluster: true
      {{- end }}
    {{- $api := index .Values "testkube-cloud-api"}}
    issuer: {{ if .Values.global.dex.issuer }}{{ .Values.global.dex.issuer }}{{ else }}https://{{ .Values.global.restApiSubdomain }}.{{ .Values.global.domain }}/idp{{ end }}
    staticClients:
      - id: {{ $api.api.oauth.clientId }}
        name: 'Testkube Enterprise'
        secret: '{{ $api.api.oauth.clientSecret }}'
        redirectURIs:
        {{- if .Values.global.domain }}
          - 'https://{{ .Values.global.restApiSubdomain }}.{{ .Values.global.domain }}/auth/callback'
        {{- else }}
          - 'http://localhost:8090/auth/callback'
          - 'http://localhost:38090/auth/callback'
        {{- end }}
      - id: testkube-cloud-cli
        name: 'Testkube Enterprise CLI'
        secret: '{{ $api.api.oauth.clientSecret }}'
        redirectURIs:
          - 'http://127.0.0.1:8090/callback'
      {{- with .Values.dex.configTemplate.additionalStaticClients }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- with .Values.dex.configTemplate.additionalConfig }}
    {{ . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
