{{- if and .Values.global.ingress.enabled .Values.minio.customIngress.enabled -}}
{{- $fullName := .Values.minio.fullnameOverride -}}
{{- if and .Values.minio.customIngress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.minio.customIngress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.minio.customIngress.annotations "kubernetes.io/ingress.class" .Values.minio.customIngress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  {{- with .Values.minio.customIngress.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: {{ if .Values.minio.tls.enabled }}HTTPS{{ else }}HTTP{{ end }}
    {{- if eq .Values.global.certificateProvider "cert-manager" }}
    cert-manager.io/cluster-issuer: {{ required ".Values.global.certManager.issuerRef must be provided if provider is cert-manager" .Values.global.certManager.issuerRef }}
    {{- end }}
    {{- with .Values.minio.customIngress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.minio.customIngress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.minio.customIngress.className }}
  {{- end }}
  tls:
    - hosts:
        - {{ include "testkube-enterprise.ingress.storageHost" . | quote }}
      secretName: {{ .Values.minio.customIngress.tls.tlsSecret }}
  rules:
    - host: {{ include "testkube-enterprise.ingress.storageHost" . | quote }}
      http:
        paths:
          - path: /
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  name: minio-api
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: minio-api
              {{- end }}
{{- end }}