{{- if and .Values.tls.serveHTTPS (eq .Values.global.certificateProvider "cert-manager") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "testkube-ai.fullname" . }}
  labels:
    {{- include "testkube-ai.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  secretName: {{ .Values.tls.tlsSecret }}
  dnsNames:
    - {{ include "testkube-ai.ingress.host" . | quote }}
  {{- with .Values.tls.certManager.duration }}
  duration: {{ . | quote }}
  {{- end }}
  issuerRef:
    name: {{ required ".Values.global.certManager.issuerRef must be set when provider is cert-manager" .Values.global.certManager.issuerRef }}
    kind: {{ .Values.tls.certManager.issuerKind }}
    group: {{ .Values.tls.certManager.issuerGroup }}
{{- end }}
