{{- if eq .Values.tls.certificateProvider "cert-manager" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "testkube-ai.fullname" . }}
  labels:
    {{- include "testkube-ai.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  secretName: {{ .Values.tls.secret }}
  dnsNames:
    -  {{ .Values.tls.host }}
  issuerRef:
    name: {{ required ".Values.global.certManager.issuerRef must be set when provider is cert-manager" .Values.tls.certManager.issuerRef }}
    kind: {{ .Values.tls.certManager.issuerKind }}
    group: {{ .Values.tls.certManager.issuerGroup }}
{{- end }}
