{{- if and .Values.global.ingress.enabled .Values.ingress.enabled -}}
{{- $fullName := include "testkube-ai.fullname" . -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "testkube-ai.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.ingress.className "nginx"}}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
    nginx.ingress.kubernetes.io/backend-protocol: {{ if .Values.tls.serveHTTPS }}HTTPS{{ else }}HTTP{{ end }}
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/client-header-timeout: "10800"
    nginx.ingress.kubernetes.io/client-body-timeout: "10800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "10800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "10800"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10800"
    {{- if and (not .Values.tls.serveHTTPS) (eq .Values.global.certificateProvider "cert-manager") }}
    cert-manager.io/cluster-issuer: {{ required ".Values.global.certManager.issuerRef must be provided if provider is cert-manager" .Values.global.certManager.issuerRef }}
    {{- end }}
    {{- end }}
    {{- if and (eq .Values.ingress.className "nginx") (.Values.tls.serveHTTPS) }}
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if eq .Values.tls.serveHTTPS false }}
  tls:
    - hosts:
        - {{ include "testkube-ai.ingress.host" . | quote }}
      secretName: {{ .Values.tls.tlsSecret }}
  {{- end }}
  rules:
    - host: {{ include "testkube-ai.ingress.host" . | quote }}
      http:
        paths:
          - path: "/"
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  name: {{ if .Values.tls.serveHTTPS }}https{{ else }}http{{ end }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ if .Values.tls.serveHTTPS }}https{{ else }}http{{ end }}
              {{- end }}
{{- end }}
