name: Release Helm charts - main

on:
  push:
    branches:
      - main
      - enterprise-chart
    paths:
      - 'charts/testkube-cloud-api/templates/**'
      - 'charts/testkube-cloud-api/Chart.yaml'
      - 'charts/testkube-cloud-api/values.yaml'
      - 'charts/testkube-cloud-api/README.md'
      - 'charts/testkube-cloud-ui/templates/**'
      - 'charts/testkube-cloud-ui/Chart.yaml'
      - 'charts/testkube-cloud-ui/values.yaml'
      - 'charts/testkube-cloud-ui/README.md'
      - 'charts/testkube-enterprise/templates/**'
      - 'charts/testkube-enterprise/Chart.yaml'
      - 'charts/testkube-enterprise/values.yaml'
      - 'charts/testkube-enterprise/README.md'
      - '.github/workflows/chart-release.yaml'

jobs:
  release-helm-charts:
    name: Release Helm charts
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "testkube-cloud-ci-bot"
          git config --global user.email "testkube-cloud-ci-bot@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Update lock file
        run: |
          ./scripts/sync.sh
#           git status
#           git add charts/testkube-enterprise/Chart.lock
#           git commit -m "updating lock file"
#           git push

      - name: Installing repositories
        run: |
          helm repo add dex https://charts.dexidp.io
          helm repo add nats https://nats-io.github.io/k8s/helm/charts/
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CR_SKIP_EXISTING: true












