name: Dispatch events based on push to sandbox branch

on:
  push:
    branches:
      - sandbox/**

jobs:
  dispatch:
    # TODO(emil): enable when the dispatch token is no longer a personal access token
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DISPATCH_GITHUB_TOKEN }}
          repository: kubeshop/testkube-deployment
          event-type: sandbox_charts_update
          client-payload: '{"ref": "${{ github.ref }}", "ref_name": "${{ github.ref_name }}", "sha": "${{ github.sha }}", "repository": "${{ github.repository }}"}'
