name: Update Helm charts - develop

on:
  push:
    branches:
      - develop

    paths:
      - 'charts/testkube-cloud-api/templates/**'
      - 'charts/testkube-cloud-api/values.yaml'
      - 'charts/testkube-cloud-ui/templates/**'
      - 'charts/testkube-cloud-ui/values.yaml'
      - 'charts/testkube-enterprise/templates/**'
      - 'charts/testkube-enterprise/values.yaml'

jobs:
  release-helm-charts:
    name: Release Helm charts
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Helm charts for safety
        run: |
          helm lint charts/testkube-cloud-ui
          helm lint charts/testkube-cloud-api
          helm lint charts/testkube-enterprise

      - name: Install Helm Docs
        uses: envoy/install-helm-docs@v1.0.0
        with:
          version: 1.11.0

      - name: Update Helm Docs
        run: |
          set -ex
          helm-docs

      - name: Commit & push changes
        run: |
          git config --global user.name "testkube-cloud-ci-bot"
          git config --global user.email "testkube-cloud-ci-bot@users.noreply.github.com"
          git status
          git add **/*README.md
          git commit -m "Updating helm-chart versions and README files"
          git push