name: Release Helm charts - develop

on:
  push:
    branches:
      - develop
      - ci/add-flow-for-develop

    paths:
      - 'charts/testkube-cloud-api/templates/**'
      - 'charts/testkube-cloud-api/Chart.yaml'
      - 'charts/testkube-cloud-api/values.yaml'
      - 'charts/testkube-cloud-api/README.md'
      - 'charts/testkube-cloud-ui/templates/**'
      - 'charts/testkube-cloud-ui/Chart.yaml'
      - 'charts/testkube-cloud-ui/values.yaml'
      - 'charts/testkube-cloud-ui/README.md'
      - 'charts/testkube-enterprise/templates/**'
      - 'charts/testkube-enterprise/Chart.yaml'
      - 'charts/testkube-enterprise/values.yaml'
      - 'charts/testkube-enterprise/README.md'

jobs:
  release-helm-charts:
    name: Release Helm charts
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Update Helm chart with changes files
        run: |
          echo "Testkube Helm charts diff"
          changed_files=$(git --no-pager diff charts)

          if [[ "$changed_files" == *"testkube-cloud-api/"* ]]; then
            echo "Changes detected in files within the 'testkube-cloud-api' directory. Updating the chart patch version."
            ./scripts/update.sh -c testkube-cloud-api --strategy patch
          else
            echo "No changes detected in the specified directories."
          fi

          if [[ "$changed_files" == *"testkube-cloud-ui/"* ]]; then
            echo "Changes detected in files within the 'testkube-cloud-ui' directory. Updating the chart patch version."
            ./scripts/update.sh -c testkube-cloud-ui --strategy patch
          else
            echo "No changes detected in the specified directories."
          fi

      - name: Update Testkube Enterprise Helm chart
        run: |

          echo "Syncing subchart versions in testkube-enterprise Helm chart"
          ./scripts/sync.sh

          echo "Bumping testkube-enterprise Helm-chart version"
          ./scripts/update.sh -c testkube-enterprise --strategy patch

      - name: Lint Helm charts for safety
        run: |
          helm lint charts/*

      - name: Commit & push changes
        run: |
          git config --global user.name "testkube-cloud-ci-bot"
          git config --global user.email "testkube-cloud-ci-bot@users.noreply.github.com"
          git status
          git add **/*Chart.yaml
          git commit -m "updating chart versions"
          git push

      - name: Generate Helm Docs
        uses: shaybentk/helm-docs-action@v0.0.1
        with:
          working-dir: charts/testkube-cloud-api,charts/testkube-cloud-ui,charts/testkube-cloud-enterprise
          git-push: "true"
